apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
    environment: ${ENVIRONMENT}
spec:
  replicas: ${APP_REPLICAS}
  selector:
    matchLabels:
      app: ${PROJECT_NAME}
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}
        environment: ${ENVIRONMENT}
    spec:
      serviceAccountName: ${PROJECT_NAME}-sa
      containers:
      - name: ${PROJECT_NAME}
        image: ${APP_IMAGE}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-url
        - name: ENVIRONMENT
          value: ${ENVIRONMENT}
        resources:
          requests:
            memory: ${APP_MEMORY_REQUEST}
            cpu: ${APP_CPU_REQUEST}
          limits:
            memory: ${APP_MEMORY_LIMIT}
            cpu: ${APP_CPU_LIMIT}
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}
  labels:
    app: ${PROJECT_NAME}
    environment: ${ENVIRONMENT}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: ${PROJECT_NAME}